### ISSUE TITLE
`irb -r app.rb` throws an error

### ISSUE THREAD

**Issue by js-coder** [janlelis/irbtools#24]
I got a `make debug` task configured to easily start debugging, it runs `irb -r app.rb`.
My `.irbrc` loads irbtools.

```ruby
require 'irbtools'
```

When I start a plain IRB session (`irb`) everything works fine, but when I add the `-r app.rb` switch this happens:

```sh
$ irb -r app.rb
Welcome to IRB. You are using ruby 1.9.3p374 (2013-01-15 revision 38858) [x86_64-darwin12.2.1]. Have fun ;)
>> 40 + 2
LoadError: Could not load colorizer Paint at /Users/florian/.rvm/gems/ruby-1.9.3-p374/gems/wirb-1.0.1/lib/wirb/colorizer/paint: cannot load such file -- paint
	from /Users/florian/.rvm/gems/ruby-1.9.3-p374/gems/wirb-1.0.1/lib/wirb.rb:41:in `eval'
	from /Users/florian/.rvm/gems/ruby-1.9.3-p374/gems/wirb-1.0.1/lib/wirb/colorizer.rb:14:in `const_missing'
	from (eval):1:in `load_colorizer'
	from /Users/florian/.rvm/gems/ruby-1.9.3-p374/gems/wirb-1.0.1/lib/wirb.rb:41:in `eval'
	from /Users/florian/.rvm/gems/ruby-1.9.3-p374/gems/wirb-1.0.1/lib/wirb.rb:41:in `load_colorizer'
	from /Users/florian/.rvm/gems/ruby-1.9.3-p374/gems/wirb-1.0.1/lib/wirb.rb:82:in `load_schema'
	from /Users/florian/.rvm/gems/ruby-1.9.3-p374/gems/wirb-1.0.1/lib/wirb.rb:47:in `schema'
	from /Users/florian/.rvm/gems/ruby-1.9.3-p374/gems/wirb-1.0.1/lib/wirb.rb:98:in `colorize_result'
	from /Users/florian/.rvm/gems/ruby-1.9.3-p374/gems/irbtools-1.4.0/lib/irbtools/libraries.rb:145:in `view_or_page_output'
	from /Users/florian/.rvm/gems/ruby-1.9.3-p374/gems/hirb-0.7.1/lib/hirb/view.rb:186:in `output_value'
	from /Users/florian/.rvm/rubies/ruby-1.9.3-p374/lib/ruby/1.9.1/irb.rb:160:in `block (2 levels) in eval_input'
	from /Users/florian/.rvm/rubies/ruby-1.9.3-p374/lib/ruby/1.9.1/irb.rb:273:in `signal_status'
	from /Users/florian/.rvm/gems/ruby-1.9.3-p374/gems/fancy_irb-0.7.3/lib/fancy_irb/irb_ext.rb:104:in `signal_status'
	from /Users/florian/.rvm/rubies/ruby-1.9.3-p374/lib/ruby/1.9.1/irb.rb:156:in `block in eval_input'
	from /Users/florian/.rvm/rubies/ruby-1.9.3-p374/lib/ruby/1.9.1/irb/ruby-lex.rb:243:in `block (2 levels) in each_top_level_statement'
	from /Users/florian/.rvm/rubies/ruby-1.9.3-p374/lib/ruby/1.9.1/irb/ruby-lex.rb:229:in `loop'
	from /Users/florian/.rvm/rubies/ruby-1.9.3-p374/lib/ruby/1.9.1/irb/ruby-lex.rb:229:in `block in each_top_level_statement'
	from /Users/florian/.rvm/rubies/ruby-1.9.3-p374/lib/ruby/1.9.1/irb/ruby-lex.rb:228:in `catch'
	from /Users/florian/.rvm/rubies/ruby-1.9.3-p374/lib/ruby/1.9.1/irb/ruby-lex.rb:228:in `each_top_level_statement'
	from /Users/florian/.rvm/rubies/ruby-1.9.3-p374/lib/ruby/1.9.1/irb.rb:155:in `eval_input'
	from /Users/florian/.rvm/rubies/ruby-1.9.3-p374/lib/ruby/1.9.1/irb.rb:70:in `block in start'
	from /Users/florian/.rvm/rubies/ruby-1.9.3-p374/lib/ruby/1.9.1/irb.rb:69:in `catch'
	from /Users/florian/.rvm/rubies/ruby-1.9.3-p374/lib/ruby/1.9.1/irb.rb:69:in `start'
	from /Users/florian/.rvm/rubies/ruby-1.9.3-p374/bin/irb:16:in `<main>'Maybe IRB bug!
```

The weird part is that this actually works fine:

```sh
$ irb
Welcome to IRB. You are using ruby 1.9.3p374 (2013-01-15 revision 38858) [x86_64-darwin12.2.1]. Have fun ;)
>> 40 + 2 #=> 42
>> load 'app.rb'  #=> true
>> 40 + 2 #=> 42
```

I guess this has something to do with the load path? Inside of app.rb I just prepend my `lib` folder `$LOAD_PATH`, but that shouldn't be a problem right?

I installed irbtools with a plain `gem install irbtools`.

**Comment by janlelis** [comment]
Closing. Please re-open with more information if this is still a problem for you.
