### ISSUE TITLE
irbtools fails for 2.7.0-preview1

### ISSUE THREAD

**Issue by ogirginc** [janlelis/irbtools#44]
When `irbtools` gem is installed, an `irb` session can't be started on Ruby `2.7.0-preview1`. Program exits with `NoMethodError` when `fancy_irb` calls [`#indent`](https://github.com/janlelis/fancy_irb/blob/master/lib/fancy_irb/irb_ext.rb#L11):

```ruby
$ irb -f -r irbtools
Welcome to IRB. You are using ruby 2.7.0preview1 (2019-05-31 trunk c55db6aa271df4a689dc8eb0039c929bf6ed43ff) [x86_64-darwin18]. Have fun ;)
Traceback (most recent call last):
	15: from /Users/ogirginc/.rvm/rubies/ruby-2.7.0-preview1/bin/irb:23:in `<main>'
	14: from /Users/ogirginc/.rvm/rubies/ruby-2.7.0-preview1/bin/irb:23:in `load'
	13: from /Users/ogirginc/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
	12: from /Users/ogirginc/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/2.7.0/irb.rb:388:in `start'
	11: from /Users/ogirginc/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/2.7.0/irb.rb:430:in `run'
	10: from /Users/ogirginc/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/2.7.0/irb.rb:430:in `catch'
	 9: from /Users/ogirginc/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/2.7.0/irb.rb:431:in `block in run'
	 8: from /Users/ogirginc/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/2.7.0/irb.rb:492:in `eval_input'
	 7: from /Users/ogirginc/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/2.7.0/irb/ruby-lex.rb:83:in `each_top_level_statement'
	 6: from /Users/ogirginc/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/2.7.0/irb/ruby-lex.rb:83:in `catch'
	 5: from /Users/ogirginc/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/2.7.0/irb/ruby-lex.rb:84:in `block in each_top_level_statement'
	 4: from /Users/ogirginc/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/2.7.0/irb/ruby-lex.rb:84:in `loop'
	 3: from /Users/ogirginc/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/2.7.0/irb/ruby-lex.rb:86:in `block (2 levels) in each_top_level_statement'
	 2: from /Users/ogirginc/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/2.7.0/irb/ruby-lex.rb:68:in `prompt'
	 1: from /Users/ogirginc/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/2.7.0/irb.rb:460:in `block in eval_input'
/Users/ogirginc/.rvm/gems/ruby-2.7.0-preview1/gems/fancy_irb-1.1.0/lib/fancy_irb/irb_ext.rb:11:in `prompt': undefined method `indent' for #<RubyLex:0x00007fe210b6be40> (NoMethodError)
```

### Additional Info

| Tool | Version |
| --- | --- |
| MacOS | 10.14.5 |
| Ruby | 2.7.0-preview1 |
| RVM | 1.29.7 |
| irbtools | 3.0.0 |

**Comment by janlelis** [comment]
Hey @ogirginc ,

thanks for reporting this bug. Could you try to upgrade fancy_irb to 1.2.0 and test if the problem still occurs?

**Comment by ogirginc** [comment]
All good with `fancy_irb` v1.2.0. Thanks! 👍
