### ISSUE TITLE
Error - NameError: uninitialized constant MethodFinder::INSTANCE_METHOD_BLACKLIST

### ISSUE THREAD

**Issue by kapso** [janlelis/irbtools#52]
When launching rails console, I am seeing the following error...

```
git:(develop) rc
Running via Spring preloader in process 56500
Loading development environment (Rails 6.1.3.2)
load error: /Users/kapil/projects/tradespace/.irbrc
NameError: uninitialized constant MethodFinder::INSTANCE_METHOD_BLACKLIST
Did you mean?  MethodFinder::INSTANCE_METHOD_IGNORELIST
	/Users/kapil/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/irbtools-3.0.4/lib/irbtools/libraries.rb:122:in `block in <main>'
	/Users/kapil/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/irbtools-3.0.4/lib/irbtools/implementation.rb:105:in `block in library_loaded'
	/Users/kapil/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/irbtools-3.0.4/lib/irbtools/implementation.rb:105:in `each'
	/Users/kapil/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/irbtools-3.0.4/lib/irbtools/implementation.rb:105:in `library_loaded'
```

**Comment by smeevil** [comment]
Same

**Comment by janlelis** [comment]
Thank you for this bug report!
