### ISSUE TITLE
Error while loading a library into IRB:

### ISSUE THREAD

**Issue by lain0** [janlelis/irbtools#56]
I just used irb in console without rails console. Irbtools works, but shows an error message on startup

```sh
Error while loading a library into IRB:

### NameError
undefined method `prompt' for class `IRB::Irb'

### STACKTRACE
  /Users/serj/.rvm/gems/ruby-3.2.2/gems/fancy_irb-2.0.0/lib/fancy_irb/irb_ext.rb:7:in `<class:Irb>'
  /Users/serj/.rvm/gems/ruby-3.2.2/gems/fancy_irb-2.0.0/lib/fancy_irb/irb_ext.rb:2:in `<module:IRB>'
  /Users/serj/.rvm/gems/ruby-3.2.2/gems/fancy_irb-2.0.0/lib/fancy_irb/irb_ext.rb:1:in `<top (required)>'
  /Users/serj/.rvm/gems/ruby-3.2.2/gems/fancy_irb-2.0.0/lib/fancy_irb/implementation.rb:20:in `require_relative'
  /Users/serj/.rvm/gems/ruby-3.2.2/gems/fancy_irb-2.0.0/lib/fancy_irb/implementation.rb:20:in `extend!'
  /Users/serj/.rvm/gems/ruby-3.2.2/gems/fancy_irb-2.0.0/lib/fancy_irb/implementation.rb:14:in `start'
  /Users/serj/.rvm/gems/ruby-3.2.2/gems/irbtools-4.0.5/lib/irbtools/libraries.rb:25:in `block in <top (required)>'
  /Users/serj/.rvm/gems/ruby-3.2.2/gems/irbtools-4.0.5/lib/irbtools/implementation.rb:84:in `block in library_loaded'
  /Users/serj/.rvm/gems/ruby-3.2.2/gems/irbtools-4.0.5/lib/irbtools/implementation.rb:84:in `each'
  /Users/serj/.rvm/gems/ruby-3.2.2/gems/irbtools-4.0.5/lib/irbtools/implementation.rb:84:in `library_loaded'
  /Users/serj/.rvm/gems/ruby-3.2.2/gems/irbtools-4.0.5/lib/irbtools/implementation.rb:95:in `block in load_libraries'
  /Users/serj/.rvm/gems/ruby-3.2.2/gems/irbtools-4.0.5/lib/irbtools/implementation.rb:92:in `each'
  /Users/serj/.rvm/gems/ruby-3.2.2/gems/irbtools-4.0.5/lib/irbtools/implementation.rb:92:in `load_libraries'
  /Users/serj/.rvm/gems/ruby-3.2.2/gems/irbtools-4.0.5/lib/irbtools.rb:33:in `block (2 levels) in <top (required)>'


Welcome to IRB. You are using ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-darwin22]. Have fun ;)
>> exit
```
Same error vs  ruby 3.1.2

```sh
Error while loading a library into IRB:

### NameError
undefined method `prompt' for class `IRB::Irb'

### STACKTRACE
  /Users/serj/.rvm/gems/ruby-3.1.2/gems/fancy_irb-2.0.0/lib/fancy_irb/irb_ext.rb:7:in `<class:Irb>'
  /Users/serj/.rvm/gems/ruby-3.1.2/gems/fancy_irb-2.0.0/lib/fancy_irb/irb_ext.rb:2:in `<module:IRB>'
  /Users/serj/.rvm/gems/ruby-3.1.2/gems/fancy_irb-2.0.0/lib/fancy_irb/irb_ext.rb:1:in `<top (required)>'
  /Users/serj/.rvm/gems/ruby-3.1.2/gems/fancy_irb-2.0.0/lib/fancy_irb/implementation.rb:20:in `require_relative'
  /Users/serj/.rvm/gems/ruby-3.1.2/gems/fancy_irb-2.0.0/lib/fancy_irb/implementation.rb:20:in `extend!'
  /Users/serj/.rvm/gems/ruby-3.1.2/gems/fancy_irb-2.0.0/lib/fancy_irb/implementation.rb:14:in `start'
  /Users/serj/.rvm/gems/ruby-3.1.2/gems/irbtools-4.0.5/lib/irbtools/libraries.rb:25:in `block in <top (required)>'
  /Users/serj/.rvm/gems/ruby-3.1.2/gems/irbtools-4.0.5/lib/irbtools/implementation.rb:84:in `block in library_loaded'
  /Users/serj/.rvm/gems/ruby-3.1.2/gems/irbtools-4.0.5/lib/irbtools/implementation.rb:84:in `each'
  /Users/serj/.rvm/gems/ruby-3.1.2/gems/irbtools-4.0.5/lib/irbtools/implementation.rb:84:in `library_loaded'
  /Users/serj/.rvm/gems/ruby-3.1.2/gems/irbtools-4.0.5/lib/irbtools/implementation.rb:95:in `block in load_libraries'
  /Users/serj/.rvm/gems/ruby-3.1.2/gems/irbtools-4.0.5/lib/irbtools/implementation.rb:92:in `each'
  /Users/serj/.rvm/gems/ruby-3.1.2/gems/irbtools-4.0.5/lib/irbtools/implementation.rb:92:in `load_libraries'
  /Users/serj/.rvm/gems/ruby-3.1.2/gems/irbtools-4.0.5/lib/irbtools.rb:33:in `block (2 levels) in <top (required)>'


Welcome to IRB. You are using ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-darwin21]. Have fun ;)
>> binding.irb
```

**Comment by janlelis** [comment]
Thanks for reporting this. The implementation of IRB itself changed - with the latest version of Irbtools/FancyIRB it should work again.
