### ISSUE TITLE
`look` command does not work as documented

### ISSUE THREAD

**Issue by okuramasafumi** [janlelis/irbtools#60]
## Description

`look` command causes a following error.

```
irb(main):3.3.4:001:0> look "str"
/Users/okuramasafumi/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/irb-1.14.0/lib/irb/context.rb:604:in `evaluate': undefined method `execute' for an instance of Symbol (NoMethodError)

        statement.command_class.execute(self, statement.arg)
                               ^^^^^^^^
	from /Users/okuramasafumi/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fancy_irb-2.1.2/lib/fancy_irb/irb_ext.rb:39:in `evaluate'
	from /Users/okuramasafumi/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/irb-1.14.0/lib/irb.rb:1049:in `block (2 levels) in eval_input'
	from /Users/okuramasafumi/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/irb-1.14.0/lib/irb.rb:1388:in `signal_status'
	from /Users/okuramasafumi/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/fancy_irb-2.1.2/lib/fancy_irb/irb_ext.rb:9:in `signal_status'
	from /Users/okuramasafumi/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/irb-1.14.0/lib/irb.rb:1041:in `block in eval_input'
	from /Users/okuramasafumi/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/irb-1.14.0/lib/irb.rb:1120:in `block in each_top_level_statement'
	from <internal:kernel>:187:in `loop'
	from /Users/okuramasafumi/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/irb-1.14.0/lib/irb.rb:1117:in `each_top_level_statement'
	from /Users/okuramasafumi/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/irb-1.14.0/lib/irb.rb:1040:in `eval_input'
	from /Users/okuramasafumi/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/irb-1.14.0/lib/irb.rb:1021:in `block in run'
	from /Users/okuramasafumi/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/irb-1.14.0/lib/irb.rb:1020:in `catch'
	from /Users/okuramasafumi/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/irb-1.14.0/lib/irb.rb:1020:in `run'
	from /Users/okuramasafumi/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/irb-1.14.0/lib/irb.rb:904:in `start'
	from /Users/okuramasafumi/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/irb-1.14.0/exe/irb:9:in `<top (required)>'
	from /Users/okuramasafumi/.rbenv/versions/3.3.4/bin/irb:25:in `load'
	from /Users/okuramasafumi/.rbenv/versions/3.3.4/bin/irb:25:in `<main>'
Maybe IRB bug!
```

As it says, it might be a bug of IRB itself.

## Environment

- Ruby: `3.3.4`
- IRB: `1.14.0`
- irbtools: `4.0.11`

**Comment by janlelis** [comment]
@okuramasafumi Thank you for reporting this! Now fixed with v4.1.0
